[project]
name = "sentiment-knowledge-distillation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "google-genai>=1.63.0",
    "ollama>=0.6.1",
]
